service: miranda-backend
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
provider:
  name: aws
  region: eu-north-1
  environment:
    TOKEN_SECRET: ${file(.env.json):TOKEN_SECRET}
    MONGO_URL: ${file(.env.json):MONGO_URL}
  runtime: nodejs20.x
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true (editado) 